name: Build and deploy a flask application
trigger:
 - master

resources:
- repo: self

variables:
 imageName: 'image-$(Build.Repository.Name):$(Build.SourceBranchName)-$(Buils.BuildId)'

stages:
- stage: Build
  displayName: Build Image And Deploy
  jobs:
  - job: Build
    displayName: Build Job
    pool: 
      vmImage: ubuntu-latest
    steps: 
    - task: Docker@2
      inputs:
        containerRegistry: 'container-registory'
        repository: 'demoacr077'
        command: 'build'
        Dockerfile: '**/Dockerfile'
    # - task: Docker@2
    #   displayName: Build docker image
    #   inputs:
    #     command: 'build'
    #     Dockerfile: '**/Dockerfile'
    #     imageName: '$(imageName)'
    - task: Docker@2
      displayName: Push the docker image
      inputs:
        containerRegistry: 'container-registory'
        repository: 'demoacr077'
        command: 'push'
        # imageName: '$(imageName)'
    
    

